on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR Agent
    steps:
      - name: PR Agent action step
        uses: Codium-ai/pr-agent@main
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config__ai__provider: "gemini"
          config__ai__model: "gemini-2.5-flash"
          GITHUB_ACTION_CONFIG__AUTO_REVIEW: "true"
          config__git_provider__pr_url: "https://github.com/DDD-Community/DDD-13-iOeS-BE/pull/${{ github.event.inputs.pr_number }}"